name: check-application

on:
  pull_request:
    branches: ["develop"]

# permissions:
#   pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checktou
        uses: actions/checkout@v4
      - name: Setup Node version 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}